spring:
  cloud:
    config:
      profile: local
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root123456
    url: jdbc:mysql://127.0.0.1:3306/sc_scaffold?characterEncoding=utf-8&useSSL=false
env: local
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
