server:
  port: 8083
spring:
  application:
    name: user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/portal?characterEncoding=utf-8&useSSL=false
env: local

